### ISSUE TITLE
No module named 'nemo.collections'

### ISSUE THREAD

**Issue by Dannynis** [NVIDIA-NeMo/NeMo#516]
when running "Introduction to End-To-End Automatic Speech Recognition" on google colab I run into:
```
import nemo
     
import nemo.collections.asr as nemo_asr

ModuleNotFoundError: No module named `'nemo.collections'`
```
I did all the steps sequentially, and they all succeeded until this block.

**Comment by Dannynis** [comment]
!pip install git+https://github.com/NVIDIA/NeMo.git
installing using git solved it

**Comment by josiewilliams13** [comment]
I successfully installed the git by running 
!pip install git+https://github.com/NVIDIA/NeMo.git

but it's still not working. any other suggestions?

**Comment by kode-git** [comment]
> I successfully installed the git by running !pip install git+https://github.com/NVIDIA/NeMo.git
> 
> but it's still not working. any other suggestions?

Did you installed correctly dependencies?

**Comment by titu1994** [comment]
That's an incorrect install - look at readme how to install from source. https://github.com/NVIDIA/NeMo#pip-from-source

**Comment by muizzhaque** [comment]
I have followed the steps but each time i'm installing nemo_toolkit['all'] two packages pynini and mecab-python3 is failing to build wheels, also tried nemo_toolkit['asr'] which was successful but as soon as i run the code, i got the same module not found error
btw, I'am using windows 10

**Comment by titu1994** [comment]
Can you paste your install command ?

**Comment by computersrmyfriends** [comment]
@titu1994 Thanks for your response.

First, I tried using the pip version etc and finally resorted to this:

`conda install pytorch torchvision torchaudio pytorch-cuda=11.8 -c pytorch -c nvidia
apt-get update && apt-get install -y libsndfile1 ffmpeg
pip install Cython
pip install nemo_toolkit['all']
git clone https://github.com/NVIDIA/NeMo
cd NeMo
./reinstall.sh`



`
Traceback (most recent call last):
  File "projects/nvidianemo2/listmodels.py", line 1, in <module>
    import nemo.collections.tts as nemo_tts
  File "nvidianemo2/nemo.py", line 7, in <module>
    from nemo.collections.asr.models import EncDecCTCModel
ModuleNotFoundError: No module named 'nemo.collections'; 'nemo' is not a package

`

**Comment by titu1994** [comment]
The issue is your file name - dont name it Nemo.py, python is trying to resolve Nemo library from hour file path (cause your file path gets pretended to Python path automatically in most ides like pycharm or code editors like vs code. 

Just renaming the file should work

**Comment by computersrmyfriends** [comment]
wow, good one. Didn't open my eyes to the stack trace. That did the trick. I didn't realize that!!

Thank you!!!!

**Comment by titu1994** [comment]
Having faced this issue more times than I care to admit, glad to see the solution is that simple 😄

**Comment by duarteocarmo** [comment]
> The issue is your file name - dont name it Nemo.py, python is trying to resolve Nemo library from your file path (cause your file path gets prepended to Python path automatically in most ides like pycharm or code editors like vs code.
> 
> Just renaming the file should work

Gets me everytime.
