### ISSUE TITLE
CONF-TSASR

### ISSUE THREAD

**Issue by valentin7121** [NVIDIA-NeMo/NeMo#8709]
The article ["Conformer-based Target-Speaker Automatic Speech Recognition for Single-Channel Audio"](https://arxiv.org/pdf/2308.05218v1.pdf) states that the model CONF-TSASR will be open-sourced through NVIDIA NeMo toolkit. Is it already open-sourced? Will pretrained weights be available? If yes, where can I found it?

**Comment by AntoineBlanot** [comment]
Up!
I wish to try it as well to check if reported results are as good as they say.
Can we already find it and if no, when will it be available?

**Comment by valentin7121** [comment]
Still waiting for the answer, thank you.

**Comment by valentin7121** [comment]
Up

**Comment by lotuscarvedlife** [comment]
wait for it

**Comment by chengjt23** [comment]
wait for it too, its results seem to be too good

**Comment by GaoXinJian-USTC** [comment]
wait fo ...... so long
